### ISSUE TITLE
creating generic functions over ToLua (or FromLua)

### ISSUE THREAD

**Issue by Grokmoo** [kyren/rlua#111]
It seems with 0.16 it is no longer possible to create functions which are generic over a ToLua or FromLua parameter outside of a context.  Is this understanding correct?

As an example, I might want to write something like the snippet below.  In 0.15, without the context, this worked fine and I don't think would cause any safety issues (at least in the cases where I was using it) - for example, T might be a String or bool.

```
fn foo<'a, T>(lua: &Lua, func_name: &str, param: T) -> Result<()>
  where T: ToLua<'a> {
  lua.context(|context| {
    let func: Function = context.globals().get(func_name)?;
    func.call::<T, ()>(param)
  })
}
```

Thanks in advance.

**Comment by kyren** [comment]
You just need to modify your function slightly:

```
fn foo<T>(lua: &Lua, func_name: &str, param: T) -> Result<()>
where
    T: for<'a> ToLua<'a>,
{
    lua.context(|context| {
        let func: Function = context.globals().get(func_name)?;
        func.call::<T, ()>(param)
    })
}
```

**Comment by Grokmoo** [comment]
Wow, thanks for the fast response!  I haven't used a higher-rank trait bound before but that makes total sense.
