### ISSUE TITLE
Generic Struct over Userdata?

### ISSUE THREAD

**Issue by ducharmemp** [kyren/rlua#120]
Hi Kyren! Sorry, second issue in the last few weeks. I'm at a bit of a loss here and I'd love for your rust-foo to help out here. I know I'm definitely delving into more of the arcane parts of rust, so hopefully this is possible. Given the below code:

```rust
struct Gen<T, M> where T: std::cmp::Eq, M: std::cmp::Eq {
    ...
}
```

Is it possible to define the constraints of the struct to *also* require that FromLua and ToLua are required? 

```rust
impl<T, M> LuaUserData for Gen<T, M> where T: std::cmp::Eq, M: std::cmp::Eq {
    fn add_methods<'lua, DM: LuaUserDataMethods<'lua, Self>>(methods: &mut DM) {
        methods.add_method("methodName", |lua_ctx, this, (t, m): (T, M)| {
            Ok(())
        });
    }
}
```

I *almost* got it to work by adding the trait bound to the impl definition, but then my method impl signature didn't match :/

```rust
impl<'lua, T: FromLua<'lua>, M: FromLua<'lua>> LuaUserData for Gen<T, M> where T: std::cmp::Eq, M: std::cmp::Eq {
    fn add_methods<DM: LuaUserDataMethods<'lua, Self>>(methods: &mut DM) {
        methods.add_method("methodName", |lua_ctx, this, (t, m): (T, M)| {
            Ok(())
        });
    }
}
```

I'm using this struct as a basic lookup table for my lua scripts to pass values up to the game state from my systems. I know that this is basically asking for Rust help rather than RLua help, but any insights would be amazing and appreciated!

**Comment by Timidger** [comment]
Only glanced at this, but can you do:

```rust
impl<'lua, T, M> LuaUserData for Gen<T, M> where T: std::cmp::Eq + FromLua<'lua>, M: std::cmp::Eq + FromLua<'lua> {
    fn add_methods<'lua, DM: LuaUserDataMethods<'lua, Self>>(methods: &mut DM) {
        methods.add_method("methodName", |lua_ctx, this, (t, m): (T, M)| {
            Ok(())
        });
    }
}
```

**Comment by ducharmemp** [comment]
@Timidger I did try your suggestion, thanks for giving it a look! Unfortunately, this causes the 'lua lifetime to be shadowed, which the compiler doesn't like because *I think* it considers them two disparate lifetimes. 

```error[E0496]: lifetime name `'lua` shadows a lifetime name that is already in scope```

The other problem with this that because the lifetimes seem to be disparate, the compiler doesn't know how to convert from the ```impl<'lua>``` to the ```add_method<'lua>```. I've tried a few more things (nothing saved because I'm basically banging away at my keyboard with a dead brain at this point) but the answer might just be that the impl needs to be specialized for this case, or I need to create a helper macro. I'm hoping there's some magic that I'm missing because this would be *really* nice to be able to have a concrete impl that's defined in my game state and it could serialize to lua without almost any issue.

**Comment by Timidger** [comment]
If you need to say one lifetime lives as long as another, use `:` syntax.

```rust

**Comment by ducharmemp** [comment]
Aha! Different error (thanks so much for the help!). "impl has stricter requirements than trait". This is definitely a new on for me...

**Comment by Timidger** [comment]
Maybe reverse the 'a and the 'lua in that, e.g. `'lua: 'a`? I always get the order confused. Though this has reached the limits of my guessing for tonight, Kyren will be more useful at this point.

**Comment by ducharmemp** [comment]
Thanks for your help @Timidger it gave me a new error which means a new research trajectory :)

**Comment by ducharmemp** [comment]
Got it. So basically, I needed to have a lifetime specifier for my struct as well and then specify that the lua lifetime would live as long as my struct lifetime. 

```

**Comment by ducharmemp** [comment]
Whoops, closed by accident, sorry all. So this *doesn't* work. In a roundabout way, I got back to the same issue since I have to specify a PhantomData attribute in the Gen struct now. I think I'm going to let this sit for the night and take a look back in the morning

**Comment by ducharmemp** [comment]
So I just realized I was *vastly* overthinking this. I'm going to look into passing in a function that wraps the struct methods I want to expose. Closing this issue, although it was a *really* good exercise for me to understand the nuances of rust's type system and lifetimes.

**Comment by kyren** [comment]
Okay, I'm on mobile so I don't know how useful I'll be, sorry in advance.

If you just want a T and M that are not Lua handles and just implement FromLua, you should do "T: for<'lua> FromLua<'lua>" (and also for M).

If you need some specific 'lua lifetime, then T and M themselves must be Lua handles that you receive as userdata method parameters, and you can't do that and it being possible to do so would be a soundness issue.

> Now this *might* be unsound because I have *no* idea what I'm really doing with lifetimes yet,

It can't be, because you haven't typed "unsafe".  If you could cause UB with that it would be my bug not yours.  That's what unsound means, code marked as safe that can be used to cause memory unsafety.  If you have no unsafe marked, it's  somebody else problem that did write "unsafe".

**Comment by ducharmemp** [comment]
Wow, that completely worked! I previously didn't know about the semantics of for within lifetimes, so thanks for the help/tip! For posterity, this is how the final generic struct looks:

```rust
struct Gen<'a, T, M> where T: std::cmp::Eq, M: std::cmp::Eq {
    ...
}

impl<T, M> LuaUserData for Gen<T, M> where T: std::cmp::Eq + for<'lua> FromLua<'lua>, M: std::cmp::Eq + for<'lua> FromLua<'lua> {
    fn add_methods<'lua, DM: LuaUserDataMethods<'lua, Self>>(methods: &mut DM) {
        methods.add_method("methodName", |lua_ctx, this, (t, m): (T, M)| {
            Ok(())
        });
    }
}
```
