### ISSUE TITLE
Why FromLua implementation for bool returns true for numbers

### ISSUE THREAD

**Issue by Hugal31** [kyren/rlua#143]
The `FromLua` implementation for `bool` returns true if the value is a `Number` or an `Integer`, even if its value is 0. Is this wanted ?

https://github.com/kyren/rlua/blob/eda13ab4675f10fbbd7fb0d57ca4e38b757f5423/src/conversion.rs#L168-L176

**Comment by kyren** [comment]
It matches the behavior of Lua itself, only nil and false are false, all other values are true.

**Comment by Hugal31** [comment]
Oh, thanks, nevermind.
