### ISSUE TITLE
Is it possible to create more than one coroutine using a single lua context

### ISSUE THREAD

**Issue by surajpayu** [kyren/rlua#144]
i am currently creating a lua coroutine from rust and calling a lua function from it. Right now, i am able to create a single coroutine from lua per lua context. I want to spawn more than one  lua coroutine in a single lua context. It looks like it is not possible to do it today. Can you suggest any way in which, I can achieve it?

**Comment by kyren** [comment]
You should be able to spawn all the coroutines you want, is something broken?

**Comment by surajpayu** [comment]
My bad, I was calling it incorrectly. Closing the issue.
