### ISSUE TITLE
What happens on Windows with -C panic=abort ?

### ISSUE THREAD

**Issue by gnzlbg** [kyren/rlua#151]
@kyren I don't know how else to contact you, so sorry for the noise here. What happens on windows when rlua is used with Rust compiled with `-C panic=abort` ? Do the `setjmp`/`longjmp`s still work ?

**Comment by kyren** [comment]
> @kyren I don't know how else to contact you, so sorry for the noise here.

That's totally fine!  This is relevant to rlua anyway.

I will check right now and get back to you

**Comment by kyren** [comment]
Okay, with the nightly as of 2019-10-14 (e413dc36a), in release, with panic set to "abort" in the release profile, this still does not seem to be an issue.

My test was simply to return an `Err` from a Lua callback, which will cause `rlua` to invoke `ffi::lua_error` inside an `extern "C"` function.  The error seems to be caught in Lua via `pcall` and makes it to the outer calling Rust code.

**Comment by gnzlbg** [comment]
Thank you so much!
