### ISSUE TITLE
Loading selected Lua libs

### ISSUE THREAD

**Issue by Piripant** [kyren/rlua#51]
As of right now, when creating a new instance of the Lua structure, all the lua libraries are automatically loaded. This is, as written in the README, undesirable.
Is there any reason this is currently like this? What do I need to know before trying to change the API to make libraries loading into a separate functions?

**Comment by kyren** [comment]
I guess we could go ahead and allow you to load individual libraries separately, but what I originally meant to allude to in the README was doing so for the purposes of security and sandboxing, which is a larger concern.

I suppose I was waiting to be more ready for a push towards security and panic / abort resistance before working on that, to see better what the API might look like.  I was originally envisioning something like safety levels, where the bottom level is intended to be completely secure / safe, and possibly when combined with execution limits even resistant to DOS, and above that a version that is definitely not secure but is sound, and finally a version that is not even sound (debug table).
