### ISSUE TITLE
Releases aren't tagged

### ISSUE THREAD

**Issue by Timidger** [kyren/rlua#72]
rlua doesn't tag its releases, which can be annoying when you want to check the source of a particular version.

**Comment by jonas-schievink** [comment]
Another opportunity to convert people to the great [cargo-release](https://github.com/sunng87/cargo-release), which can automate this process

**Comment by kyren** [comment]
I have tagged at least one release now (0.13.0)!  Also, cargo-release is great!  Should I go back and tag the previous releases?

**Comment by Timidger** [comment]
It would be nice, but is not necessary. I found out you didn't when trying to pin-point possible regressions, so it's up to you since these latest releases are changing a lot this might not be necessary.

**Comment by kyren** [comment]
Is there a regression I should know about?  Even if you don't have a lot of good data I can work on figuring it out.

**Comment by Timidger** [comment]
There was an issue we were running into with recursive calls to the index function on Way Cooler. However, we worked around it by using the latest version. Not so much a "regression" as that we were changing over to using the user value API and not everything worked the first time.

Nothing for you to fix, so don't worry.

**Comment by kyren** [comment]
Ohhhh okay, hopefully the change to use Fns as well as FnMuts helped that issue?

Also sorry in general for all the API churn.

**Comment by Timidger** [comment]
Yep that was it, IIRC.

No worries. I'm not focusing too much on the Lua API right now anyways since I'm trynig to get [wlroots-rs](https://github.com/swaywm/wlroots-rs) done. Seems like you are finally finding an API that works, which is what matters.

**Comment by kyren** [comment]
I'm actually glad you mentioned it, because I was convinced to add that feature almost solely so I could write a test that hit the Lua C API recursion limits :P  I figured SOMEBODY would need recursive functions though, so now I'm glad I added it and I see that you were at least one of those somebodies!
