### ISSUE TITLE
Support for lua_sethook

### ISSUE THREAD

**Issue by beatgammit** [kyren/rlua#81]
This might be a safety nightmare, so I wanted to get your input before looking into implementation. Here are the production use-cases:

* running untrusted code submitted from users (stop infinite loops)
* pre-empting a CPU-heavy lua script in an async event loop

And then there's the typical debugging tasks, but I think those can be done within lua with the current debug library.

From #52, it looks like the debug library is considered "unsafe", and I'm not sure if this can be done safely. In any case, I'd really like be able to handle the above use cases.

I created a similar issue on hlua ([#194](https://github.com/tomaka/hlua/issues/194)), just in case discussion in the other project is useful here.

I'm willing to do work on this, but I'd like to know your thoughts on feasibility first.

EDIT: This is essentially the first bullet point in the README (and perhaps the second).

**Comment by kyren** [comment]
This is now added!

Running untrusted code using PUC-Rio Lua (by itself or via `rlua`, in any way really) is risky in a lot of ways.  I added some information to the README about this so that the sandboxing pieces of the `rlua` API did not become an "attractive nuisance".
