### ISSUE TITLE
Non-utf8 string support

### ISSUE THREAD

**Issue by vorner** [kyren/rlua#94]
Hello

Lua's strings allow whatever inside them. This is in odds with what Rust mandates from its `str` and `String`. However, the API mostly translates the Lua strings to Rust's `str`, at least in the direction Rust → Lua. Which is mostly OK, but at times it is needed to pass data that is not guaranteed to be utf8 ‒ content of lua script from file, `PathBuf`, or outright binary blob (which lua usually stores as string too).

This is from the lua documentation:

> The type string represents immutable sequences of bytes. Lua is 8-bit clean: strings can contain any 8-bit value, including embedded zeros ('\0'). Lua is also encoding-agnostic; it makes no assumptions about the contents of a string. 

What would be a good way to allow sending arbitrary sequence of bytes to lua? It doesn't have to be the most convenient one, but not being able to pass it seems limiting.

**Comment by kyren** [comment]
Yeah, you should be able to create non-utf8 strings, but you can't right now.

I'll look at adding that capability before the next release.

**Comment by kyren** [comment]
Is something like 167184ae76b37b53114f2818bbc48c83936a08f4 what you're looking for?  There's no automatic conversion from &[u8] which I guess there *could* be, but it seems a bit dangerous and implicit somehow.

**Comment by vorner** [comment]
Yes, something like that, thank you ☺

However:
* If there was something like `BytString(pub Vec<u8>)` implementing `FromLua` and `ToLua`, it would add to the convenience without introducing the implicitness.
* There are still spots in the API where it is impossible to pass eg. a valid (non-utf8) lua program to the system. But these are probably less severe limitations.

**Comment by kyren** [comment]
I can also change the API to allow non-utf8 lua programs, I can't really think of a reason not to.

As far as making something like a custom ByteString type, I think that's probably something that would be better for users of the library to use.  Also, making such a wrapper take a Vec<u8> could potentially be very wasteful since Lua wouldn't adopt the storage behind the Vec, it has to copy in all cases.

**Comment by kyren** [comment]
Okay, that's changed and added to 0.15, I probably shouldn't have tried to do this change at the very last minute before releasing 0.15, but oh well.

There's a lot of things I didn't change to non-utf8 that I theoretically could.  For example, the names of UserData methods are not changed, the source identifiers for chunks are not changed, and named registry keys are not changed.

Probably it should all be consistent, but some of those changes are somewhat involved, so it'll have to wait for the next version.

**Comment by vorner** [comment]
Thank you, it looks like it's working :-).

As for the others… I don't think these are that important. Especially the registry keys and source identifiers are well in hand of the rust code, and having non-ascii (or non-utf8) method names is very unlikely.
