### ISSUE TITLE
Missing math.pow

### ISSUE THREAD

**Issue by Arnaz87** [kyren/rlua#99]
The function `math.pow` is missing, math and all the other functions are there but not pow

**Comment by poga** [comment]
Lua 5.3 removed `math.pow`, use `x^y` instead.

**Comment by Arnaz87** [comment]
oh right, but my local lua 5.3.5 installation still has that function

**Comment by Arnaz87** [comment]
You are right, math.pow is not in the documentation anymore, maybe someone forgot to remove it in my version

**Comment by FreeMasen** [comment]
deprecation and removal are not entirely the same. It would be nice to have the ability to build the embedded Lua with `LUA_COMPAT_MATHLIB`, to allow for usage of deprecated math functions as they would be provided by a default installation of the language.

**Comment by jugglerchris** [comment]
I agree it sounds reasonable to be able to configure the Lua library used.  Maybe this can come out of the work on #191 .

**Comment by FreeMasen** [comment]
While I understand the desire to batch this change with another version of rlua, I was hoping this would be available with lua 5.3 since a consumer moving from 5.3 -> 5.4 is more than just dealing with this difference.
